name: deploy
on:
  workflow_call:

jobs:
  flydeploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Deploy to Fly
        run: echo "would run flyctl deploy here"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
